# Generated by Django 3.0.5 on 2020-04-19 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calender_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calenderslot',
            name='belongs_to',
            field=models.ForeignKey(help_text='\n    Stores the user the slot belongs to.\n    ', on_delete=django.db.models.deletion.CASCADE, related_name='created_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calenderslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='\n    Django auto populates this field whenever a slot is created by a user.\n    '),
        ),
        migrations.AlterField(
            model_name='calenderslot',
            name='end_time',
            field=models.DateTimeField(help_text='\n    Contains the end time of the slot.\n    '),
        ),
        migrations.AlterField(
            model_name='calenderslot',
            name='start_time',
            field=models.DateTimeField(help_text='\n    Contains the start time of the slot.\n    '),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, help_text='\n    Django automatically populates this field whenever a slot is booked.\n    '),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='booked_by',
            field=models.ForeignKey(help_text='\n    Contains the user who has booked the slot. If it was booked by an anonymous user, it is None.\n    ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='description',
            field=models.TextField(help_text='\n    Contains some booking data entered by the person who booked the slot.\n    ', null=True),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='slot',
            field=models.OneToOneField(help_text='\n    References to the slot that is booked.\n    ', on_delete=django.db.models.deletion.CASCADE, related_name='booking_details', to='calender_mgmt.CalenderSlot'),
        ),
    ]
